set_theme() {
  case $1 in
  dragon)
    white=$old_white
    gray=$dragon_black_4
    dark_gray=$dragon_black_2
    light_purple=$dragon_orange
    dark_purple=$dragon_black_5
    cyan=$dragon_teal
    green=$dragon_ash
    orange=$dragon_yellow
    red=$dragon_red
    pink=$dragon_orange
    yellow=$dragon_yellow
    ;;
  oxocarbon)
    white=$oxocarbon_white
    gray=$oxocarbon_gray
    dark_gray=$oxocarbon_dark_gray
    light_purple=$oxocarbon_light_purple
    dark_purple=$oxocarbon_dark_purple
    cyan=$oxocarbon_cyan
    green=$oxocarbon_green
    orange=$oxocarbon_orange
    red=$oxocarbon_red
    pink=$oxocarbon_pink
    yellow=$oxocarbon_yellow
    ;;
  *)
    white=$mocha_white
    gray=$mocha_gray
    dark_gray=$mocha_dark_gray
    light_purple=$mocha_light_purple
    dark_purple=$mocha_dark_purple
    cyan=$mocha_cyan
    green=$mocha_green
    orange=$mocha_orange
    red=$mocha_red
    pink=$mocha_pink
    yellow=$mocha_yellow
    ;;
  esac
}
